spring.application.name=backend
server.port=8080
logging.level.org.springframework.web=DEBUG
spring.mvc.log-request-details=true

# Database configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/jira
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.generate-ddl=true
spring.jpa.show-sql=true

#JWT
jwt.secret=3m6B9epqA2dX5gYrKvPwS8zUyLxJhN4cRfT7kWtZnQ0MbG1VlCsOaD4Ie5FoHj
jwt.expiration=86400

#Email
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=20203tn160@utez.edu.mx
spring.mail.password=kapg qtej ilhc slpg
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.smtp.conectiontimeout=10000
spring.mail.properties.smtp.timeout=10000
spring.mail.properties.smtp.writetimeout=10000

#Swagger
openapi.dev-url=http://localhost:8080

# Swagger UI custom path
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha
springdoc.swagger-ui.tryItOutEnabled=true
springdoc.swagger-ui.filter=true